spring.application.name=bd
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/produtosbd}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
